### ISSUE TITLE
Refresh error when going to a different tab and then back to your site

### ISSUE THREAD

**Issue by jahirfiquitiva** [brianlovin/briOS#1791]
![Shot 2021-11-10 at 22-48-46](https://user-images.githubusercontent.com/10360816/141234145-9152cd3c-06b8-4b16-b15e-1e304b3f0dd7.gif)

**Comment by brianlovin** [comment]
Wow, good catch. I'm going to rip out some of my logic to refetch on `window.focus` because of this, I'm not _quite_ sure what's causing that jumpy behavior.

**Comment by brianlovin** [comment]
Patching with https://github.com/brianlovin/briOS/pull/1794/commits/381b4162cab1cbb24d2b50a022faa875ebdf2c27
