### ISSUE TITLE
Navigation overlay stays after changing viewport

### ISSUE THREAD

**Issue by jahirfiquitiva** [brianlovin/briOS#1792]
![Shot 2021-11-10 at 22-50-43](https://user-images.githubusercontent.com/10360816/141234237-d1271b3f-1fe4-4a09-8182-8a85496c0c78.gif)

**Comment by brianlovin** [comment]
Thanks for the heads up! I think I'll call this a `wont fix` since it's nearly impossible for someone to hit this state in normal usage.
