### ISSUE TITLE
Not able to sign in on iPhone with Safari

### ISSUE THREAD

**Issue by jahirfiquitiva** [brianlovin/briOS#1800]
Hey Brian, I was trying to sign in to post something on AMA, but for some reason the button wasn't showing in Safari.

I'm using an iPhone 12 Pro, if that provides any helpful info.

Thanks!

https://user-images.githubusercontent.com/10360816/141681387-db6f47ec-453c-4e36-a852-0629361ce53c.mp4

**Comment by brianlovin** [comment]
Hey @jahirfiquitiva I believe this is because of an ad blocker. Do you have any Safari extensions you're running on your phone that might be causing this?

**Comment by jahirfiquitiva** [comment]
Oh, you're right. I just checked and disabled those and is working as expected. Sorry for the inconvenience, and thank you for the response! 😅
