### ISSUE TITLE
Banner on blog posts has unreadable text in dark mode (Safari Mobile)

### ISSUE THREAD

**Issue by sekeidesign** [brianlovin/briOS#1928]
![image](https://user-images.githubusercontent.com/59372630/150053100-0ea32022-e811-4cb0-a946-350f69fc90aa.jpeg)

Scrolled down this blog post to find the header turned light whilst the heading was also white making it illegible 🌚

**Comment by brianlovin** [comment]
Thanks! I pushed out a buggy color fix yesterday, I'll wrap this up today.
