### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by XahidEx** [brianlovin/briOS#1983]
There are no deployment guidelines. It's a beautiful site. And I think It should have a deployment guide. Or just include which environment variables are mandatory. Just like me, Getting confused about it. 😁.

**Comment by brianlovin** [comment]
Hey, thanks for the note — I haven't prioritized making it super simple to replicate this so that only motivated folks will go through and piece it together. The code is mostly open source in case people want to reference any particular view or idea 😊

**Comment by XahidEx** [comment]
Got it.. But we learners sometimes have less patience. Because It's really so incredible.. 🙈
