### ISSUE TITLE
Sign in link cut off on mobile

### ISSUE THREAD

**Issue by iamnbutler** [brianlovin/briOS#1988]
Tested in safari and chrome on iOS.

Looks like something is causing the signin link at the bottom of the mobile navigation to get cut off.

![image](https://user-images.githubusercontent.com/1714999/175828290-f4711199-1a11-41b2-ab16-4bea87d2a41b.png)

Second link when pulling beyond the bottom:

![image](https://user-images.githubusercontent.com/1714999/175828306-197e6657-cd8a-40a0-b517-b0d48f4dcfbf.png)

**Comment by brianlovin** [comment]
Thanks for the issue! Responsive web is janky in a lot of ways still, unfortunately 😞 — will work on this when I have the time!

**Comment by iamnbutler** [comment]
No worries of course! Just a heads up. Agreed, mobile web is a struggle to prioritize 😅
