### ISSUE TITLE
Please provide instructions on how to run/deploy an instance of your briOS

### ISSUE THREAD

**Issue by AnthonyAkentiev** [brianlovin/briOS#2002]
Hello Brian! Your briOS is a wonderful tool that I want to use.

I really want to launch my version of briOS (with full credits of course!).
Would be great if you provide us with the README and .env file examples to ease up the deployment of briOS. 

I have encountered an old "ENV stub" here - https://github.com/brianlovin/briOS/blob/e664155ff97e4abb55efcbb7a3b7151e35c53639/now.json  

Can you please help with the instructions?
Anton

**Comment by brianlovin** [comment]
Thanks @AnthonyAkentiev — I don't plan to spend time on documentation right now, but if you manage to get it working, a PR on the README is welcome 😊
